name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          # ⛔ remove cache: 'pnpm' here

      - name: Install pnpm (with cache)
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
          cache: true                 # handles pnpm store caching for you

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('next.config.*', 'app/**', 'components/**', 'lib/**') }}
          restore-keys: |
            ${{ runner.os }}-next-${{ matrix.node }}-

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Tests with coverage
        run: pnpm run test:cov -- --run

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage/**
